package com.example.productcatalogservice.services.listener;

import com.example.productcatalogservice.models.ProductOfferingPriceAttributeValueChangeEvent;

public interface ProductOfferingPriceAttributeValueChangeEventService {
    ProductOfferingPriceAttributeValueChangeEvent save(ProductOfferingPriceAttributeValueChangeEvent productOfferingPriceAttributeValueChangeEvent);
}
