package com.example.productcatalogservice.repositories.listener;

import com.example.productcatalogservice.models.ProductOfferingAttributeValueChangeEvent;
import org.springframework.data.mongodb.repository.MongoRepository;

public interface ProductOfferingAttributeValueChangeEventRepository extends MongoRepository<ProductOfferingAttributeValueChangeEvent,String> {
}
